 <WANIPConnection instance="1">
          <Enable>TRUE</Enable>
          <Reset>FALSE</Reset>
          <ConnectionStatus>Unconfigured</ConnectionStatus>
          <PossibleConnectionTypes>Unconfigured, IP_Routed, IP_Bridged</PossibleConnectionTypes>
          <ConnectionType>IP_Routed</ConnectionType>
          <Name>3_INTERNET_R_VID_3351</Name>
          <Alias>(null)</Alias>
          <Uptime>0</Uptime>
          <X_BROADCOM_COM_ConnectionEstablishedTime>0</X_BROADCOM_COM_ConnectionEstablishedTime>
          <LastConnectionError>ERROR_NONE</LastConnectionError>
          <AutoDisconnectTime>0</AutoDisconnectTime>
          <IdleDisconnectTime>0</IdleDisconnectTime>
          <WarnDisconnectDelay>0</WarnDisconnectDelay>
          <NATEnabled>TRUE</NATEnabled>
          <X_BROADCOM_COM_FullconeNATEnabled>FALSE</X_BROADCOM_COM_FullconeNATEnabled>
          <AddressingType>DHCP</AddressingType>
          <ExternalIPAddress></ExternalIPAddress>
          <SubnetMask>0.0.0.0</SubnetMask>
          <DefaultGateway></DefaultGateway>
          <X_BROADCOM_COM_FirewallEnabled>TRUE</X_BROADCOM_COM_FirewallEnabled>
          <X_BROADCOM_COM_IGMPEnabled>TRUE</X_BROADCOM_COM_IGMPEnabled>
          <DNSEnabled>TRUE</DNSEnabled>
          <DNSOverrideAllowed>FALSE</DNSOverrideAllowed>
          <DNSServers></DNSServers>
          <MaxMTUSize>1492</MaxMTUSize>
          <PeerMaxMRUSize>2000</PeerMaxMRUSize>
          <MACAddress>00:85:56:df:80:16</MACAddress>
          <MACAddressOverride>FALSE</MACAddressOverride>
          <PPPoEACName>(null)</PPPoEACName>
          <PPPoEServiceName>(null)</PPPoEServiceName>
          <ConnectionTrigger>AlwaysOn</ConnectionTrigger>
          <RouteProtocolRx>Off</RouteProtocolRx>
          <X_BROADCOM_COM_RipOperationMode>Passive</X_BROADCOM_COM_RipOperationMode>
          <X_BROADCOM_COM_RipDebugMode>(null)</X_BROADCOM_COM_RipDebugMode>
          <X_BROADCOM_COM_IfName>epon0.2</X_BROADCOM_COM_IfName>
          <X_BROADCOM_COM_ConnectionId>2</X_BROADCOM_COM_ConnectionId>
          <X_BROADCOM_COM_DhcpcPid>0</X_BROADCOM_COM_DhcpcPid>
          <X_TWSH_COM_VlanMode>DEFAULT</X_TWSH_COM_VlanMode>
          <X_TWSH_COM_Tpid>33024</X_TWSH_COM_Tpid>
          <X_BROADCOM_COM_VlanMux8021p>0</X_BROADCOM_COM_VlanMux8021p>
          <X_BROADCOM_COM_VlanMuxID>3351</X_BROADCOM_COM_VlanMuxID>
          <X_BROADCOM_COM_ROUTEMARK>0</X_BROADCOM_COM_ROUTEMARK>
          <ShapingRate>-1</ShapingRate>
          <ShapingBurstSize>0</ShapingBurstSize>
          <PortMappingNumberOfEntries>0</PortMappingNumberOfEntries>
          <X_BROADCOM_COM_Op60VenderID>(null)</X_BROADCOM_COM_Op60VenderID>
          <X_BROADCOM_COM_Op61DUID>(null)</X_BROADCOM_COM_Op61DUID>
          <X_BROADCOM_COM_Op61IAID>(null)</X_BROADCOM_COM_Op61IAID>
          <X_BROADCOM_COM_Op125Enabled>FALSE</X_BROADCOM_COM_Op125Enabled>
          <X_BROADCOM_COM_IPv6Enabled>TRUE</X_BROADCOM_COM_IPv6Enabled>
          <X_CU_IPForwardModeEnabled>FALSE</X_CU_IPForwardModeEnabled>
          <X_CU_IPForwardList>(null)</X_CU_IPForwardList>
          <X_CT_COM_IPV4Enable>FALSE</X_CT_COM_IPV4Enable>
          <X_CT-COM_IPMode>2</X_CT-COM_IPMode>
          <X_BROADCOM_COM_UnnumberedModel>FALSE</X_BROADCOM_COM_UnnumberedModel>
          <X_BROADCOM_COM_IPv6ConnStatus>Connected</X_BROADCOM_COM_IPv6ConnStatus>
          <X_BROADCOM_COM_IPv6AddressingType>DHCP</X_BROADCOM_COM_IPv6AddressingType>
          <X_BROADCOM_COM_Dhcp6cForAddress>FALSE</X_BROADCOM_COM_Dhcp6cForAddress>
          <X_CU_IPv6IPAddressAlias>(null)</X_CU_IPv6IPAddressAlias>
          <X_BROADCOM_COM_ExternalIPv6Address>(null)</X_BROADCOM_COM_ExternalIPv6Address>
          <X_BROADCOM_COM_IPv6_Uptime>66</X_BROADCOM_COM_IPv6_Uptime>
          <X_BROADCOM_COM_ConnectionIPv6EstablishedTime>0</X_BROADCOM_COM_ConnectionIPv6EstablishedTime>
          <X_BROADCOM_COM_ExternalIPv6AddressPrefixLength>0</X_BROADCOM_COM_ExternalIPv6AddressPrefixLength>
          <X_BROADCOM_COM_IPv6DefaultConnectionService>FALSE</X_BROADCOM_COM_IPv6DefaultConnectionService>
          <X_BROADCOM_COM_IPv6DNSEnabled>TRUE</X_BROADCOM_COM_IPv6DNSEnabled>
          <X_BROADCOM_COM_DefaultIPv6Gateway>fe80::20c:29ff:fe8f:b413</X_BROADCOM_COM_DefaultIPv6Gateway>
          <X_BROADCOM_COM_IPv6DNSServers>2111:9c:103:0:c:135:9a:a15,2111:9c:103:0:3bc6:a:9cc:518</X_BROADCOM_COM_IPv6DNSServers>
          <X_CU_IPv6DomainName>(null)</X_CU_IPv6DomainName>
          <X_BROADCOM_COM_IPv6PrefixDelegationEnabled>TRUE</X_BROADCOM_COM_IPv6PrefixDelegationEnabled>
          <X_CU_IPv6PrefixAlias>(null)</X_CU_IPv6PrefixAlias>
          <X_BROADCOM_COM_IPv6SitePrefix>2111:9671:7b4c:8000::/56</X_BROADCOM_COM_IPv6SitePrefix>
          <X_BROADCOM_COM_IPv6SitePrefixPltime>7200</X_BROADCOM_COM_IPv6SitePrefixPltime>
          <X_BROADCOM_COM_IPv6SitePrefixVltime>172800</X_BROADCOM_COM_IPv6SitePrefixVltime>
          <X_BROADCOM_COM_Dhcp6cPid>4818</X_BROADCOM_COM_Dhcp6cPid>
          <X_BROADCOM_COM_MLDEnabled>TRUE</X_BROADCOM_COM_MLDEnabled>
          <X_CT-COM_IPV6Enable>TRUE</X_CT-COM_IPV6Enable>
          <X_BROADCOM_COM_LastConnected>FALSE</X_BROADCOM_COM_LastConnected>
          <X_CT-COM_LanInterface>(null)</X_CT-COM_LanInterface>
          <X_CT-COM_ServiceList>INTERNET</X_CT-COM_ServiceList>
          <X_CMCC_VLANMode>0</X_CMCC_VLANMode>
          <X_CMCC_802-1pMark>0</X_CMCC_802-1pMark>
          <X_CT-COM_LanInterface-DHCPEnable>TRUE</X_CT-COM_LanInterface-DHCPEnable>
          <X_BROADCOM_COM_IPv6BondingMode>0</X_BROADCOM_COM_IPv6BondingMode>
          <X_BROADCOM_COM_IPv6BondingBridge>Default</X_BROADCOM_COM_IPv6BondingBridge>
          <X_CT-COM_MulticastVlan>-1</X_CT-COM_MulticastVlan>
          <X_CT-COM_Dslite_Enable>FALSE</X_CT-COM_Dslite_Enable>
          <X_CT-COM_AftrMode>0</X_CT-COM_AftrMode>
          <X_CT-COM_Aftr>(null)</X_CT-COM_Aftr>
          <X_CT-COM_IPv6IPAddressOrigin>AutoConfigured</X_CT-COM_IPv6IPAddressOrigin>
          <X_CT-COM_IPv6PrefixOrigin>PrefixDelegation</X_CT-COM_IPv6PrefixOrigin>
          <X_CU_VLANEnabled>FALSE</X_CU_VLANEnabled>
          <X_CU_IGMPProxyEnable>TRUE</X_CU_IGMPProxyEnable>
          <X_CT-COM_IPForwardList>(null)</X_CT-COM_IPForwardList>
          <X_CT-COM_UpstreamWAN>FALSE</X_CT-COM_UpstreamWAN>
          <X_CU_DMZ>
            <DMZEnable>FALSE</DMZEnable>
            <DMZHostIPAddress>(null)</DMZHostIPAddress>
          </X_CU_DMZ>
        </WANIPConnection>