# Generated by Django 4.1 on 2023-09-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Chice", new_name="Choice",),
    ]
