# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\mypython\GUI\Pyqt5\watch\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QDateTime, Qt
from PyQt5.QtWidgets import QApplication


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.desktop = QApplication.desktop()
        self.screeenRect = self.desktop.screenGeometry()
        self.height = self.screeenRect.height()
        self.width = self.screeenRect.width()
        print(self.height, self.width)

        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1366, 768)
        MainWindow.showFullScreen()
        MainWindow.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint)  # 无边框 置顶

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 0, self.width, self.height))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber.setStyleSheet("border: 5px solid black; color: white; background: black;")
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setSmallDecimalPoint(True)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.time = QTimer()
        self.time.timeout.connect(self.showTime)
        self.time.start(1000)

        self.retranslateUi(MainWindow)
        self.lcdNumber.windowIconTextChanged['QString'].connect(MainWindow.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def initUI(self):
        self.QWidget.setWindowTitle("statusBar")
        self.QWidget.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint)  # 无边框 置顶
        self.QWidget.window().setAttribute(Qt.WA_TranslucentBackground)  # 透明背景色
        self.QWidget.showFullScreen()

    def showTime(self):
        # 获取系统当前时间
        time = QDateTime.currentDateTime()
        # 设置系统时间的显示格式
        # timeDisplay = time.toString('hh:mm:ss')
        timeDisplay = time.toString('hh:mm')
        # 在标签上显示时间
        self.lcdNumber.display(timeDisplay)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
